# Change these first
owner: ittp # Your GitHub organization or username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
    - name: github
      url: https://api.github.com/status
#   - name: api
#     url: https://api.ittps.ru
#   - name: vpn
#     url: https://vpn.ittps.ru
  
#   - name: Test for HEAD
#     method: HEAD
#     url: https://api.github.com/

#   - name: Secret Site
#     url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 # cname: update.ittps.ru
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ittp upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
